[workspace]
members = [
    "ctaphid-protocol",
    "fido2-authenticator-api",
    "fido2-authenticator-service",
    "linux/uhid-sys",
    "linux/uhid-tokio",
    "linux/uhid-tokio/example",
    "linux/user-daemon",
    "linux/system-daemon",
    "linux/test-authenticator",
    "u2f-core",
]

[profile.release]
lto = true
panic = 'abort'
